version: 2.1
jobs:
  test:
    docker:
      - image: cimg/python:3.11  # Python image
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install numpy pandas matplotlib scipy pytest
      - run:
          name: Run unit tests
          command: pytest test_Fit_Synthetic_Data.py
workflows:
  version: 2
  test_workflow:
    jobs:
      - test